# This is a basic workflow to help you get started with Actions

name: Test 

on:
 
  push:
    branches: [ "*" ]
    
jobs:

ci:

    runs-on: ubuntu-latest

    steps:
    
      - uses: actions/checkout@v3
      - uses : actiions/seetup-node@v2
        node-version: 10
      - run: npm ci
      - run: npm run jest
      - run: npm run build
